### ISSUE TITLE
Support for linkedin and youtube icons

### ISSUE THREAD

**Issue by alberto56** [hatch130/steward-2021-redesign#1]
Hi @SiteNineStudios can you please add linkedin and youtube in addition to facebook, twitter...

See enclosed image

<img width="519" alt="Screen Shot 2021-05-19 at 8 53 27 AM" src="https://user-images.githubusercontent.com/808265/118816055-d216d080-b87f-11eb-9b4c-b0c8459b39ce.png">

**Comment by SiteNineStudios** [comment]
Hi @alberto56 

We have added CSS for linkedin and youtube fonts / icons in latest commited file.

**Comment by alberto56** [comment]
Works great, thanks.
